# Generated by Django 4.0.4 on 2022-05-21 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_languages_remove_country_languages_country_languages'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='country',
        #     name='languages',
        # ),
        # migrations.AddField(
        #     model_name='country',
        #     name='languages',
        #     field=models.CharField(default=django.utils.timezone.now, max_length=200),
        #     preserve_default=False,
        # ),
        migrations.DeleteModel(
            name='Country'

        ),
    ]
